### ISSUE TITLE
Support option to look up vhost based on proxied destination address/port

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_proxy_protocol#3]
Some sites might want to use the PROXY protocol to not only preserve the originating client IP address, but also to use the original destination address/port to do the vhost lookup.  The proxied destination address/port are currently ignored by mod_proxy_protocol.

**Comment by mfuterko** [comment]
Hi @Castaglia. It's definitely a useful functionality we would rely on. Do you have any plans to progress with it? I'd be happy to help with testing and feedback, as always. Thanks, Mike.

**Comment by Castaglia** [comment]
@mfuterko I don't have any particular plans for this -- but mostly because I'm not aware of particular use cases that `mod_proxy_protocol` users might have for such a feature.

Can you explain better what you might need this feature for, how you would envision using it?  That'll help me figure out a test harness, with which to verify any development for this.

**Comment by Castaglia** [comment]
This has now been implemented in master.  Thanks!
